entity_mapping = {
                        "7 ELEVEN TOKYO": "7ELEVEN",
                        "CLIP MX*CENTRO DE VAC": "CENTRO DE VACUNACION",
                        "STARBUCKS COFFEE": "STARBUCKS",
                        "STARBUCKS STORE": "STARBUCKS",
                        "STARBUCKS UNITED STATES": "STARBUCKS",
                        "STARBUCKS GERMANY": "STARBUCKS",
                        "STARBUCKS BOSTON": "STARBUCKS",
                        "OXXO GAS":"OXXO",
                        "OPENPAY*HELPHBOMAXCOM": "HBOMAX",
                        "AME*HMCOM": "H&M",
                        "AME*H & M II": "H&M",
                        "MASSIMO DUTTI COM": "MASSIMO DUTTI",
                        "AMAZON MX MARKETPLACE": "AMAZON",
                        "AMAZON MX MARKETP": "AMAZON",
                        "AMAZON MX": "AMAZON",
                        "VIVA AEROBUS CIB": "VIVAAEROBUS",
                        "VIVAAEROBUS WEB APODACA": "VIVAAEROBUS",
                        "APPLE ONLINE STOR": "APPLE.COM",
                        "APPLE.COM/BILL": "APPLE.COM",
                        "AME*SPOTIFY": "SPOTIFY",
                        "AMAZON COM": "AMAZON",
                        "D LOCAL*DIDI RIDES": "DIDI",
                        "STRIPE*UBER TRIP": "UBER",
                        "STR*UBER TRIP": "UBER",
                        "UBER   TRIP": "UBER",
                        "7 ELEVEN T 2020": "7ELEVEN",
                        "F AHORRO MT": "FARMACIAS DEL AHORRO",
                        "HM MX000 FASHI": "H&M",
                        "F AHORRO MTRO": "FARMACIAS DEL AHORRO",
                        "AEROMEXICO WEB PN": "AEROMEXICO",
                        "7 ELEVEN": "7ELEVEN",
                        "DLOCAL*DIDI FOOD MX": "DIDI FOOD",
                        "DLOCAL *DIDIFOOD": "DIDI FOOD",
                        "D LOCAL*DIDIFOOD": "DIDI FOOD",
                        "DLOCAL*DIDI RIDES MX": "DIDI",
                        "PAYU LA*ADIDAS MX": "ADIDAS",
                        "HEB TEXAS": "HEB",
                        "TH CANADA": "TIM HORTONS",
                        "OXXO DESCARTES": "OXXO",
                        "SUBWAY AICM T2": "SUBWAY",
                        "OXXO GAS MEXICO": "OXXO",
                        "STARBUCKS NUEVO LEON": "STARBUCKS",
                        "PAYUMEX*ADIDAS": "ADIDAS",
                        "OXXO CDMX": "OXXO",
                        "HM": "H&M",
                        "HM MX": "H&M",
                        "WALMART VENTA EN LIN3": "WALMART",
                        "BENAV": "FARMACIAS BENAVIDES",
                        "ABONO BBVA D LOCAL*DIDIFOOD":"DIDI FOOD",
                        "SPEI NOMINA": "Nomina",
                        "CARGO TR:    0 TARJ": "PAGO TARJETA DE CREDITO",
                        "SPEI. HSBC. YOUR NAME.": "HSBC YOUR NAME",
                        "SPEI. BBVA MEXICO. YOUR NAME.": "BBVA YOUR NAME",
                        "SPEI.BBVA MEXICO.0123456.YOUR NAME.":"BBVA YOUR NAME",
                        "AMAZON MX MARKETPLACE": "AMAZON",
                        "AMAZON MX": "AMAZON",
                        "AME*H & M II": "H&M",
                        "AME*HMCOM": "H&M",
                        "Devolución:AME*H & M II": "H&M",
                        "DLOCAL*DIDI RIDES": "DIDI",
                        "12748 ZARAMEXICO": "ZARA",
                        "ZARA PZA": "ZARA",
                        "AME*H & M II": "H&M",
                        "ZARA E COMMERCE": "ZARA",
                        "DEVOLUCION: ZARA E COMMER": "ZARA",
                        "AMAZON MX MARKETPLACE": "AMAZON",
                        "OXXO GAS Mexico": "OXXO",
                        "F AHORRO MEXICO": "FARMACIAS DEL AHORRO",
                        "HEB DALLAS": "HEB",
                        "WALMART VENTA EN LIN3": "WALMART",
                        "AME*FARMACIAS DEL AHO": "FARMACIAS DEL AHORRO",
                        "D LOCAL*DIDI RIDES": "DIDI",
                        "STRIPE*UBER TRIP": "UBER",
                        "IHERB IHERB.COM WnKnG": "IHERB",
                        "TH VANCOUVER":"TIM HORTONS",
                        "Adidas AMERICA, INC.":"ADIDAS",
                        "CONEKTA*MUSEO DE ARTE":"MUSEO MARCO",
                        "PAYPAL*CRUNCHYROLL":"CRUNCHYROLL",
                        "CMZH MANEJO DEL DOLOR": "HOSPITAL ZAMBRANO HELLION",
                        "TARGET": "TARGET",
                        "WENDY'S 9645": "WENDYS",
                        "HAWAIIAN AIRLINES HILO HILO":"HAWAIIAN AIRLINES",
                        "AMERICAN AIRLINES 86108 MONTERREY":"AMERICAN AIRLINES",
                        "MAGOOSH, INC.      SAN FRANCISCO":"MAGOOSH",
                        "PF CHANGS NUEVO SUR":"PF CHANGS",
                        "CINEPOLIS APP ALIMENTO MORELIA MICH":"CINEPOLIS",
                        "AMAZON MX MARKETPLACE*A MEXICO CITY":"AMAZON",
                        "STARBUCKS STORE 2179  LAKE BUENA VIST":"STARBUCKS STORE",
                        "PAYPAL *MUSEOMARCO MUSE 4029357733":"MUSEO MARCO",
                        "PAYPAL*CRUNCHYROLL":"CRUNCHYROLL",
                        "CLIP MX*REST ROCA BLAN":"REST ROCA BLAN"

                }